### ISSUE TITLE
[RaspberryPi] New Python-Version for "energy_total" throws exception

### ISSUE THREAD

**Issue by r-hof** [lumapu/ahoy#353]
### Platform

RaspberryPi

### Model name

Raspberry Pi Model 2

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

board

### Connection diagram

According to instructions

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

newest

### Github Hash

n/a

### Build & Flash Method

ESP Tools (flash)

### Desktop

Linux

### Debug Serial Log output

```shell
Exception catched: 'energy_total'
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rspitz/strom/ahoy.orig/hoymiles/__main__.py", line 319, in <module>
    main_loop(do_init)
  File "/home/rspitz/strom/ahoy.orig/hoymiles/__main__.py", line 29, in main_loop
    poll_inverter(inverter, do_init)
  File "/home/rspitz/strom/ahoy.orig/hoymiles/__main__.py", line 111, in poll_inverter
    print(f'{c_datetime} Decoded: temp={data["temperature"]}, total={data["energy_total"]/1000:.3f}', end='')
KeyError: 'energy_total'
```

**Comment by r-hof** [comment]
Sorry, please delete. Error on my part :-(
