### ISSUE TITLE
RPI list index out of range error

### ISSUE THREAD

**Issue by aenemy1** [lumapu/ahoy#874]
## Hardware
  * [ ] ESP8266
  * [ ] ESP32
  * [X] Raspberry Pi

Modelname: Rpi Zero, 
Retailer URL: ______

### nRF24L01+ Module
* [X] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [X] external antenna (SMA)

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: lastest RPI
Github Hash: _______

### Build & Flash Method:
* [ ] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

----------- DESCRIPTION ------------------------------------------------------

My setup Rpi Zero with external antenna was running fine with hoymiles HM600 and two panels for ~ 2 month.
Recently I changed over to an HM 1200, kept panels, rpi and any everything else, just changed the S/N in the ahoy.yml and now receiving an error message once ahoy connects to the inverter.
PS: An esp 8266 running ahoy works fine with that HM 1200

-------- BASH  ---------------------------------

```
pi@raspberrypi:/DTU $ python3 -um hoymiles --verbose  -c /home/pi/DTU/ahoy.yml
Using python Module: RF24
Traceback (most recent call last):
  File "/home/pi/DTU/hoymiles/__main__.py", line 146, in main_loop
    poll_inverter(inverter, dtu_ser, do_init, 3)
  File "/home/pi/DTU/hoymiles/__main__.py", line 226, in poll_inverter
    logging.info(f'Decoded: {result.__dict__()}')
  File "/home/pi/DTU/hoymiles/decoders/__init__.py", line 178, in __dict__
    data['strings'] = self.strings
  File "/home/pi/DTU/hoymiles/decoders/__init__.py", line 158, in strings
    string['name'] = self.inv_strings[string_id]['s_name']
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/DTU/hoymiles/__main__.py", line 404, in <module>
    main_loop(ahoy_config)
  File "/home/pi/DTU/hoymiles/__main__.py", line 146, in main_loop
    poll_inverter(inverter, dtu_ser, do_init, 3)
  File "/home/pi/DTU/hoymiles/__main__.py", line 226, in poll_inverter
    logging.info(f'Decoded: {result.__dict__()}')
  File "/home/pi/DTU/hoymiles/decoders/__init__.py", line 178, in __dict__
    data['strings'] = self.strings
  File "/home/pi/DTU/hoymiles/decoders/__init__.py", line 158, in strings
    string['name'] = self.inv_strings[string_id]['s_name']
IndexError: list index out of range
pi@raspberrypi:/DTU $ 
```

----------- LOG ------------

2023-04-10 09:52:41 INFO: start logging for my_DTU_name with level: 10
2023-04-10 09:52:41 INFO: Todays sunset is at 2023-04-10 18:15:00 UTC
..... REMOVED connection trys......
2023-04-10 09:59:01 INFO: Poll inverter name=balkon ser=  xxxxxxxxxxxxxx (REMOVED)
2023-04-10 09:59:03 INFO: model_decoder: Hm1200Decode0B - mirco-inverters status data
2023-04-10 09:59:03 CRITICAL: Exception catched: list index out of range
2023-04-10 09:59:03 CRITICAL: None

---------- ahoy.yml  ------------------------------------------------------
```

ahoy:
  interval: 20

  logging:
    filename: 'hoymiles.log'
    # DEBUG, INFO, WARNING, ERROR, FATAL
    level: 'DEBUG'

  sunset:
    disabled: false
    latitude: 49.9586035
    longitude: 9.9128511
    altitude: 1450

  # List of available NRF24 transceivers
  nrf:
    - ce_pin: 22
      cs_pin: 0
      txpower: 'low' # default txpower (min,low,high,max)

  mqtt:
    disabled: true
    host: 10.0.0.100
    port: 1883
    user: 'username'
    password: 'password'
    useTLS: False
    insecureTLS: False #set True for e.g. self signed certificates. 
    QoS: 0
    Retain: True
    last_will:
        topic: my_DTU_name     # Name of DTU - default: hoymiles/{DTU-serial}
        payload: "LAST-WILL-MESSAGE: Please check my HOST and Process!"

  # Influx2 output
  influxdb:
    disabled: true
    url: 'http://influxserver.local:8086'
    org: 'myorg'
    token: '<base64-token>'
    bucket: 'telegraf/autogen'
    measurement: 'hoymiles'

  volkszaehler:
    disabled: true
    inverters:
      - serial: 114172220003
        url: 'http://localhost/middleware/'
        channels:
          - type: 'ac_frequency0'
            uid:  ''
          - type: 'ac_power0'
            uid:  '7ca5ac50-1e41-11ed-927f-610c4cb2c69e'
          - type: 'ac_voltage0'
            uid:  '9a38e2e0-1d94-11ed-b539-25f8607ac030'
          - type: 'ac_current0'
            uid:  'a9a4daf0-1e41-11ed-b68c-eb73eef3d21d'
          - type: 'ac_reactive_power0'
            uid:  ''
          - type: 'dc_power0'
            uid:  '38eb3ca0-1e53-11ed-b830-792e70a592fa'
          - type: 'dc_voltage0'
            uid:  ''
          - type: 'dc_current0'
            uid:  ''
          - type: 'dc_energy_total0'
            uid:  ''
          - type: 'dc_energy_daily0'
            uid:  'c2a93ea0-9a4e-11ed-8000-7d82e3ac8959'
          - type: 'dc_irradiation0'
            uid:  'c2d887a0-9a4e-11ed-a7ac-0dab944fd82d'
          - type: 'dc_power1'
            uid:  '51c0e9d0-1e53-11ed-b574-8bc81547eb8f'
          - type: 'dc_voltage1'
            uid:  ''
          - type: 'dc_current1'
            uid:  ''
          - type: 'dc_energy_total1'
            uid:  ''
          - type: 'dc_energy_daily1'
            uid:  'c3c04df0-9a4e-11ed-82c6-a15a9aba54a3'
          - type: 'dc_irradiation1'
            uid:  'c3f3efd0-9a4e-11ed-9a77-3fd3187e6237'
          - type: 'temperature'
            uid:  'ad578a40-1d97-11ed-8e8b-fda01a416575'
          - type: 'powerfactor'
            uid:  ''
          - type: 'yield_total'
            uid:  ''
          - type: 'yield_today'
            uid:  'c4a76dd0-9a4e-11ed-b79f-2de013d39150'
          - type: 'efficiency'
            uid:  'c4d8e9c0-9a4e-11ed-9d9e-9737749e4b45'

  dtu:
    serial: 99978563001
    name: my_DTU_name

  inverters:
    - name: 'balkon'
      serial:  #REMOVED 
      txpower: 'high'                      # txpower per inverter (min,low,high,max)
      mqtt:
        send_raw_enabled: false           # allow inject debug data via mqtt
        topic: 'hoymiles/114172220003'    # defaults to '{inverter-name}/{serial}'
      strings:                            # list all available strings
      - s_name: 'String 1 left'           # String 1 name
        s_maxpower: 395                   # String 1 max power in inverter
      - s_name: 'String 2 right'          # String 2 name
        s_maxpower: 400                   # String 2 max power in inverter
      - s_name: 'String 3 up'             # String 3 name
        s_maxpower: 405                   # String 3 max power in inverter
      - s_name: 'String 4 down'           # String 4 name
        s_maxpower: 410                   # String 4 max power in inverter

```

**Comment by aenemy1** [comment]
I did find a fix for this. please forgive me, my python skills are poor.. here'S what I found:

/decoders/__init__.py
line 158: I found that this while loop runs 5 time, while the config only has 4 strings mentioned. so I changed into a for loop (not nice, I know)

` #while s_exists:
i = 1,2,3,4
s=1
for s in i:
            s_exists = False
            string_id = len(strings)
            string = {}
            string['name'] = self.inv_strings[string_id]['s_name']
            for key in self.string_keys:
                prop = f'dc_{key}_{string_id}'
                if hasattr(self, prop):
                    s_exists = True
                    string[key] = getattr(self, prop)
            if s_exists:
                strings.append(string)

        return strings`

now next thing that I noticed, irradiadation paramter is only avl. in 1st string. Mqtt will complain so I changed outputs.py in line  268 by simply commenting it out.

MQTT is broadcasting values now. Some devs should, however have a look here as I believe s.th. must be wrong using a 4 input inverter vs 2 (hm600 vs hm1200)
